name: Docker Image CI

on:
  push:
    tags: ['*']
    branches: [ "main" ]

jobs:
  docker_image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    env:
      IMAGENAME: docker.ori.triplet.gmbh/ori:${{ github.ref_name }}
      VERSION: ${{ github.ref_name }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Docker registry
      run: echo "$DOCKER_PASSWORD" | docker login docker.ori.triplet.gmbh -u "$DOCKER_USERNAME" --password-stdin

    - name: Build the Docker image
      run: docker build --tag "$IMAGENAME" --build-arg=VERSION="$VERSION" --file Dockerfile .

    - name: Push the Docker image
      run: docker push $IMAGENAME
