name: Docker Image CI

on:
  push:
    tags: ['*']
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker_image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    env:
      IMAGENAME: docker.ori.triplet.gmbh/ori:${{ github.ref_name }}
      BUILD_NAME: ${{ vars.GITHUB_REF_NAME }}
      BUILD_HASH: ${{ vars.GITHUB_SHA }}
    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.ori.triplet.gmbh -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build --tag $IMAGENAME --file Dockerfile .

    - name: Push the Docker image
      run: docker push $IMAGENAME

  deploy:
    if: startsWith(github.ref_name, 'prod-')
    name: "Deploy to Server"
    runs-on: ubuntu-latest
    needs: docker_image

    steps:
    - name: "install ansible"
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible openssh-client
        echo umask 0077
        echo "{{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "{{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy via Ansible
      run: ansible-playbook playbooks/docker.yml
      working-directory: ./devops/ansible


